//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Your Company Name")]
[assembly: AssemblyProduct("Sample.Project")]
[assembly: AssemblyCopyright("Copyright (c) Your Company Name (Year)")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("2.0.1006.2808")]
[assembly: AssemblyFileVersion("2.0.1006.2808")]


