ALTER DATABASE SampleProject
SET SINGLE_USER --or RESTRICTED_USER
WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE SampleProject;
GO

ALTER DATABASE SampleProject_Tests
SET SINGLE_USER --or RESTRICTED_USER
WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE SampleProject_Tests;
GO
go