//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example.Project.Tools.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Example.Project.Tools.Templates.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #foreach($ns in $service.Namespaces)
        ///using ${ns};
        ///#end
        ///
        ///namespace ${opt.Namespace}.Services
        ///{
        ///    public partial interface ${interface} : ${service.MakeImplementingSignature(${interface})}
        ///    {
        ///#foreach($method in $service.Methods)
        ///        ${method.MakeSignature()};
        ///#end
        ///    }
        ///}.
        /// </summary>
        internal static string AutoContracts {
            get {
                return ResourceManager.GetString("AutoContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using System.Web.Mvc.Ajax;
        ///using ${opt.Namespace}.Domain;
        ///using ${opt.Namespace}.Web.Helpers;
        ///using Simple.Validation;
        ///using Simple.Web.Mvc;
        ///
        ///namespace ${opt.Namespace}.Web.Controllers
        ///{
        ///    [SimpleValidationFilter]
        ///    public class ${classname_2}Controller : Controller
        ///    { 
        ///        public ActionResult Index()
        ///        {
        ///            return View(${classname}.ListAll());
        ///        }
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using Simple.Reflection;
        ///using Simple.Entities;
        ///using ${opt.Namespace}.Services;
        ///
        ///namespace ${opt.Namespace}.Domain
        ///{
        ///    [Serializable]
        ///    public partial class $classname : Entity&lt;${classname}, I${classname}Service&gt;
        ///    {
        ///#foreach($field in $table.PrimaryKeysExceptFk)
        ///        public virtual $re.TypeFor($field) $re.NameFor($field) { get; set; } 
        ///#end
        ///
        ///#foreach($field in $table.OrdinaryFields)
        ///        pub [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using Simple.Entities;
        ///using ${opt.Namespace}.Domain;
        ///
        ///namespace ${opt.Namespace}.Services
        ///{
        ///    public partial interface I${classname}Service : IEntityService&lt;${classname}&gt;
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string IService {
            get {
                return ResourceManager.GetString("IService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;hibernate-mapping xmlns=&quot;urn:nhibernate-mapping-2.2&quot; namespace=&quot;${opt.Namespace}.Domain&quot;&gt;
        ///  &lt;class name=&quot;${opt.Namespace}.Domain.$classname, ${opt.ContractsAssembly}&quot; table=&quot;$table.Name&quot; schema=&quot;$table.Schema&quot; #if (!${opt.LazyLoad}) lazy=&quot;false&quot; #end&gt;
        ///#if ($count.Invoke($table.PrimaryKeyColumns) &gt; 1)
        ///    &lt;composite-id&gt;
        ///    #foreach($field in $table.PrimaryKeysExceptFk)
        ///      &lt;key-property name=&quot;$re.NameFor($field)&quot; column=&quot;$field.Name&quot; /&gt;
        ///    #end
        ///    #foreac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mapping {
            get {
                return ResourceManager.GetString("Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using Simple.Migrator.Framework;
        ///using Simple.Migrator.Fluent;
        ///using System.Data;
        ///
        ///namespace ${opt.Namespace}.Tools.Migrations
        ///{
        ///    [Migration(${timestamp})]
        ///    public class Migration${timestamp} : FluentMigration
        ///    {
        ///        public override void Up()
        ///        {
        ///            /* try
        ///            Schema.AddTable(&quot;table_name&quot;, t =&gt;
        ///            {
        ///                //id column is added automatically
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewMigration {
            get {
                return ResourceManager.GetString("NewMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using Simple.Entities;
        ///using ${opt.Namespace}.Domain;
        ///
        ///namespace ${opt.Namespace}.Services
        ///{
        ///    public partial class ${classname}Service : EntityService&lt;${classname}&gt;, I${classname}Service
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using ${opt.Namespace}.Domain;
        ///using FluentValidation;
        ///
        ///namespace ${opt.Namespace}.Validators
        ///{
        ///    public class ${classname}Validator : AbstractValidator&lt;${classname}&gt;
        ///    {
        ///        public ${classname}Validator()
        ///        {
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Validator {
            get {
                return ResourceManager.GetString("Validator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Page Title=&quot;&quot; Language=&quot;C#&quot; MasterPageFile=&quot;~/Views/Shared/Site.Master&quot; Inherits=&quot;System.Web.Mvc.ViewPage&lt;${classname}&gt;&quot; %&gt;
        ///
        ///&lt;asp:Content ID=&quot;Content1&quot; ContentPlaceHolderID=&quot;MainContent&quot; runat=&quot;server&quot;&gt;
        ///    &lt;%= Html.PageTitle(&quot;New ${classname}&quot;, &quot;Fill data.&quot;) %&gt;
        ///    &lt;% Html.RenderPartial(&quot;_Form&quot;); %&gt;
        ///&lt;/asp:Content&gt;
        ///&lt;asp:Content ID=&quot;Content2&quot; ContentPlaceHolderID=&quot;HeaderContent&quot; runat=&quot;server&quot;&gt;
        ///&lt;/asp:Content&gt;
        ///.
        /// </summary>
        internal static string ViewCreate {
            get {
                return ResourceManager.GetString("ViewCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Page Title=&quot;&quot; Language=&quot;C#&quot; MaintainScrollPositionOnPostback=&quot;true&quot; MasterPageFile=&quot;~/Views/Shared/Site.Master&quot;
        ///    Inherits=&quot;System.Web.Mvc.ViewPage&lt;${classname}&gt;&quot; %&gt;
        ///
        ///&lt;asp:Content ID=&quot;Content1&quot; ContentPlaceHolderID=&quot;MainContent&quot; runat=&quot;server&quot;&gt;
        ///    &lt;%= Html.PageTitle(&quot;Details&quot;, &quot;See the details here&quot;) %&gt;
        ///    &lt;fieldset&gt;
        ///        &lt;p&gt;
        ///            &lt;label for=&quot;Name&quot;&gt;
        ///                Name:&lt;/label&gt;
        ///            &lt;span&gt;
        ///                &lt;%= Html.Encode(Model.Name) %&gt;&lt;/span&gt;
        ///        &lt;/p&gt;
        ///        &lt;p&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Page Title=&quot;&quot; Language=&quot;C#&quot; MasterPageFile=&quot;~/Views/Shared/Site.Master&quot; Inherits=&quot;System.Web.Mvc.ViewPage&lt;${classname}&gt;&quot; %&gt;
        ///
        ///&lt;asp:Content ID=&quot;Content1&quot; ContentPlaceHolderID=&quot;MainContent&quot; runat=&quot;server&quot;&gt;
        ///    &lt;%= Html.PageTitle(&quot;Edit ${classname}&quot;, &quot;Fill data.&quot;) %&gt;
        ///    &lt;% Html.RenderPartial(&quot;_Form&quot;); %&gt;
        ///&lt;/asp:Content&gt;
        ///&lt;asp:Content ID=&quot;Content2&quot; ContentPlaceHolderID=&quot;HeaderContent&quot; runat=&quot;server&quot;&gt;
        ///&lt;/asp:Content&gt;
        ///.
        /// </summary>
        internal static string ViewEdit {
            get {
                return ResourceManager.GetString("ViewEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Control Language=&quot;C#&quot; Inherits=&quot;System.Web.Mvc.ViewUserControl&lt;${classname}&gt;&quot; %&gt;
        ///&lt;% using (Html.BeginForm())
        ///   {%&gt;
        ///&lt;fieldset&gt;
        ///    &lt;p&gt;
        ///        &lt;label for=&quot;Name&quot;&gt;
        ///            Name:&lt;/label&gt;
        ///        &lt;%= Html.TextBox(&quot;Name&quot;) %&gt;
        ///        &lt;%= Html.ValidationMessage(&quot;Name&quot;, &quot;*&quot;) %&gt;
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        &lt;%= Html.BackLink(Url.Action(&quot;Index&quot;), &quot;back&quot;) %&gt;
        ///        &lt;%= Html.Submit(&quot;send&quot;) %&gt;
        ///    &lt;/p&gt;
        ///&lt;/fieldset&gt;
        ///&lt;% } %&gt;
        ///.
        /// </summary>
        internal static string ViewForm {
            get {
                return ResourceManager.GetString("ViewForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Page Title=&quot;&quot; Language=&quot;C#&quot; MasterPageFile=&quot;~/Views/Shared/Site.Master&quot; Inherits=&quot;System.Web.Mvc.ViewPage&lt;IEnumerable&lt;${classname}&gt;&gt;&quot; %&gt;
        ///
        ///&lt;asp:Content ID=&quot;Content1&quot; ContentPlaceHolderID=&quot;MainContent&quot; runat=&quot;server&quot;&gt;
        ///   
        ///    &lt;%= Html.PageTitle(&quot;${classname_2}&quot;, &quot;All ${classname_2}.&quot;) %&gt;
        ///    &lt;p&gt;
        ///        &lt;%= Html.ActionLink(&quot;new ${classname}&quot;, &quot;Create&quot;, null, new { @class = &quot;button&quot; })%&gt;
        ///    &lt;/p&gt;
        ///    &lt;% if (Model.Any())
        ///       { %&gt;
        ///    &lt;table&gt;
        ///        &lt;thead&gt;
        ///            &lt;tr&gt;
        ///                &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewIndex {
            get {
                return ResourceManager.GetString("ViewIndex", resourceCulture);
            }
        }
    }
}
