//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Living Consultoria")]
[assembly: AssemblyProduct("Simple.Net")]
[assembly: AssemblyCopyright("Copyright (c) Living Consultoria 2009")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: AssemblyVersion("3.0.1005.411")]
[assembly: AssemblyFileVersion("3.0.1005.411")]


