// <autogenerated>
//   This file was generated by T4 code generator DataClasses1.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace Simple.Generator
{
    using System;
    using System.ComponentModel;
    using System.Data.Linq;
    using System.Data.Linq.Mapping;

    [Table(Name = "dbo.Suppliers")]
    public partial class Supplier : INotifyPropertyChanging, INotifyPropertyChanged
    {
        private int supplierID;
        private string companyName;
        private string contactName;
        private string contactTitle;
        private string address;
        private string city;
        private string region;
        private string postalCode;
        private string country;
        private string phone;
        private string fax;
        private string homePage;
        private EntitySet<Product> products;
        
        public Supplier()
        {
            this.products = new EntitySet<Product>(this.AttachProducts, this.DetachProducts);
            this.OnCreated();
        }
        
        public event PropertyChangingEventHandler PropertyChanging;
        
        public event PropertyChangedEventHandler PropertyChanged;

        [Column(Name = "SupplierID", Storage = "supplierID", CanBeNull = false, DbType = "Int NOT NULL IDENTITY", IsDbGenerated = true, IsPrimaryKey = true)]
        public int SupplierID
        {
            get
            {
                return this.supplierID;
            }
        
            set
            {
                if (this.supplierID != value)
                {
                    this.OnSupplierIDChanging(value);
                    this.SendPropertyChanging("SupplierID");
                    this.supplierID = value;
                    this.SendPropertyChanged("SupplierID");
                    this.OnSupplierIDChanged();
                }
            }
        }

        [Column(Name = "CompanyName", Storage = "companyName", CanBeNull = false, DbType = "NVarChar(40) NOT NULL")]
        public string CompanyName
        {
            get
            {
                return this.companyName;
            }
        
            set
            {
                if (this.companyName != value)
                {
                    this.OnCompanyNameChanging(value);
                    this.SendPropertyChanging("CompanyName");
                    this.companyName = value;
                    this.SendPropertyChanged("CompanyName");
                    this.OnCompanyNameChanged();
                }
            }
        }

        [Column(Name = "ContactName", Storage = "contactName", CanBeNull = true, DbType = "NVarChar(30)")]
        public string ContactName
        {
            get
            {
                return this.contactName;
            }
        
            set
            {
                if (this.contactName != value)
                {
                    this.OnContactNameChanging(value);
                    this.SendPropertyChanging("ContactName");
                    this.contactName = value;
                    this.SendPropertyChanged("ContactName");
                    this.OnContactNameChanged();
                }
            }
        }

        [Column(Name = "ContactTitle", Storage = "contactTitle", CanBeNull = true, DbType = "NVarChar(30)")]
        public string ContactTitle
        {
            get
            {
                return this.contactTitle;
            }
        
            set
            {
                if (this.contactTitle != value)
                {
                    this.OnContactTitleChanging(value);
                    this.SendPropertyChanging("ContactTitle");
                    this.contactTitle = value;
                    this.SendPropertyChanged("ContactTitle");
                    this.OnContactTitleChanged();
                }
            }
        }

        [Column(Name = "Address", Storage = "address", CanBeNull = true, DbType = "NVarChar(60)")]
        public string Address
        {
            get
            {
                return this.address;
            }
        
            set
            {
                if (this.address != value)
                {
                    this.OnAddressChanging(value);
                    this.SendPropertyChanging("Address");
                    this.address = value;
                    this.SendPropertyChanged("Address");
                    this.OnAddressChanged();
                }
            }
        }

        [Column(Name = "City", Storage = "city", CanBeNull = true, DbType = "NVarChar(15)")]
        public string City
        {
            get
            {
                return this.city;
            }
        
            set
            {
                if (this.city != value)
                {
                    this.OnCityChanging(value);
                    this.SendPropertyChanging("City");
                    this.city = value;
                    this.SendPropertyChanged("City");
                    this.OnCityChanged();
                }
            }
        }

        [Column(Name = "Region", Storage = "region", CanBeNull = true, DbType = "NVarChar(15)")]
        public string Region
        {
            get
            {
                return this.region;
            }
        
            set
            {
                if (this.region != value)
                {
                    this.OnRegionChanging(value);
                    this.SendPropertyChanging("Region");
                    this.region = value;
                    this.SendPropertyChanged("Region");
                    this.OnRegionChanged();
                }
            }
        }

        [Column(Name = "PostalCode", Storage = "postalCode", CanBeNull = true, DbType = "NVarChar(10)")]
        public string PostalCode
        {
            get
            {
                return this.postalCode;
            }
        
            set
            {
                if (this.postalCode != value)
                {
                    this.OnPostalCodeChanging(value);
                    this.SendPropertyChanging("PostalCode");
                    this.postalCode = value;
                    this.SendPropertyChanged("PostalCode");
                    this.OnPostalCodeChanged();
                }
            }
        }

        [Column(Name = "Country", Storage = "country", CanBeNull = true, DbType = "NVarChar(15)")]
        public string Country
        {
            get
            {
                return this.country;
            }
        
            set
            {
                if (this.country != value)
                {
                    this.OnCountryChanging(value);
                    this.SendPropertyChanging("Country");
                    this.country = value;
                    this.SendPropertyChanged("Country");
                    this.OnCountryChanged();
                }
            }
        }

        [Column(Name = "Phone", Storage = "phone", CanBeNull = true, DbType = "NVarChar(24)")]
        public string Phone
        {
            get
            {
                return this.phone;
            }
        
            set
            {
                if (this.phone != value)
                {
                    this.OnPhoneChanging(value);
                    this.SendPropertyChanging("Phone");
                    this.phone = value;
                    this.SendPropertyChanged("Phone");
                    this.OnPhoneChanged();
                }
            }
        }

        [Column(Name = "Fax", Storage = "fax", CanBeNull = true, DbType = "NVarChar(24)")]
        public string Fax
        {
            get
            {
                return this.fax;
            }
        
            set
            {
                if (this.fax != value)
                {
                    this.OnFaxChanging(value);
                    this.SendPropertyChanging("Fax");
                    this.fax = value;
                    this.SendPropertyChanged("Fax");
                    this.OnFaxChanged();
                }
            }
        }

        [Column(Name = "HomePage", Storage = "homePage", CanBeNull = true, DbType = "NText", UpdateCheck = UpdateCheck.Never)]
        public string HomePage
        {
            get
            {
                return this.homePage;
            }
        
            set
            {
                if (this.homePage != value)
                {
                    this.OnHomePageChanging(value);
                    this.SendPropertyChanging("HomePage");
                    this.homePage = value;
                    this.SendPropertyChanged("HomePage");
                    this.OnHomePageChanged();
                }
            }
        }

        [Association(Name = "Supplier_Product", Storage = "products", ThisKey = "SupplierID", OtherKey = "SupplierID")]
        public EntitySet<Product> Products
        {
            get 
            {
                return this.products; 
            }
        
            set 
            { 
                this.products.Assign(value); 
            }
        }
        
        protected virtual void SendPropertyChanging(string propertyName)
        {
            if (this.PropertyChanging != null)
            {
                this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
            }
        }
        
        protected virtual void SendPropertyChanged(string propertyName)
        {
            if (this.PropertyChanged != null)
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
        
        private void AttachProducts(Product entity)
        {
            this.SendPropertyChanging("Products");
            entity.Supplier = this;
        }
        
        private void DetachProducts(Product entity)
        {
            this.SendPropertyChanging("Products");
            entity.Supplier = null;
        }
        
        #region Extensibility methods
        
        partial void OnCreated();
        
        partial void OnLoaded();
        
        partial void OnValidate(ChangeAction action);
        
        partial void OnSupplierIDChanging(int value);
        
        partial void OnSupplierIDChanged();
        
        partial void OnCompanyNameChanging(string value);
        
        partial void OnCompanyNameChanged();
        
        partial void OnContactNameChanging(string value);
        
        partial void OnContactNameChanged();
        
        partial void OnContactTitleChanging(string value);
        
        partial void OnContactTitleChanged();
        
        partial void OnAddressChanging(string value);
        
        partial void OnAddressChanged();
        
        partial void OnCityChanging(string value);
        
        partial void OnCityChanged();
        
        partial void OnRegionChanging(string value);
        
        partial void OnRegionChanged();
        
        partial void OnPostalCodeChanging(string value);
        
        partial void OnPostalCodeChanged();
        
        partial void OnCountryChanging(string value);
        
        partial void OnCountryChanged();
        
        partial void OnPhoneChanging(string value);
        
        partial void OnPhoneChanged();
        
        partial void OnFaxChanging(string value);
        
        partial void OnFaxChanged();
        
        partial void OnHomePageChanging(string value);
        
        partial void OnHomePageChanged();
        
        #endregion
    }
}
